.define res_string_status_loading_desktop "Apple II DeskTop starten..."
.define res_string_menu_bar_item_file "Archief"
.define res_string_menu_bar_item_edit "Wijzig"
.define res_string_menu_bar_item_view "Weergave"
.define res_string_menu_bar_item_special "Speciaal"
.define res_string_menu_bar_item_startup "Opstart"
.define res_string_menu_bar_item_selector "Opdrachten"
.define res_string_menu_item_new_folder "Nieuwe map"
.define res_char_menu_item_new_folder_shortcut 'N'
.define res_string_menu_item_open "Open"
.define res_char_menu_item_open_shortcut 'O'
.define res_string_menu_item_close "Sluit"
.define res_string_menu_item_close_all "Sluit alles"
.define res_string_menu_item_select_all "Selecteer alles"
.define res_char_menu_item_select_all_shortcut 'A'
.define res_string_menu_item_copy_selection "Kopieer naar..."
.define res_string_menu_item_delete_selection "Wissen"
.define res_string_menu_item_eject "Verwijder schijf"
.define res_char_menu_item_eject_shortcut 'E'
.define res_string_menu_item_quit "Stop"
.define res_char_menu_item_quit_shortcut 'Q'
.define res_string_menu_item_cut "Knip"
.define res_char_menu_item_cut_shortcut 'X'
.define res_string_menu_item_copy "Kopieer"
.define res_char_menu_item_copy_shortcut 'C'
.define res_string_menu_item_paste "Plak"
.define res_char_menu_item_paste_shortcut 'V'
.define res_string_menu_item_clear "Wis"
.define res_string_menu_item_by_icon "als Symbolen"
.define res_string_menu_item_by_small_icon "als Kleine Symbolen"
.define res_string_menu_item_by_name "op Naam"
.define res_string_menu_item_by_date "op Datum"
.define res_string_menu_item_by_size "op Grootte"
.define res_string_menu_item_by_type "op Soort"
.define res_string_menu_item_check_all_drives "Controleer alle stations"
.define res_string_menu_item_check_drive "Controleer station"
.define res_string_menu_item_format_disk "Schijf formatteren..."
.define res_string_menu_item_erase_disk "Schijf wissen..."
.define res_string_menu_item_disk_copy "Schijf kopi\x10ren..."
.define res_string_menu_item_make_link "Maak alias aan"
.define res_string_menu_item_show_original "Toon origineel"
.define res_string_menu_item_get_info "Toon info"
.define res_char_menu_item_get_info_shortcut 'I'
.define res_string_menu_item_rename_icon "Wijzig naam"
.define res_string_menu_item_duplicate "Dupliceer"
.define res_char_menu_item_duplicate_shortcut 'D'
.define res_string_new_folder_default "New.Folder"
.define res_string_about_text_line5 "Auteurs: Stephane Cavril, Bernard Gallet, Henri Lamiraux"
.define res_string_about_text_line6 "Richard Danais en Luc Barthelet"
.define res_string_about_text_line7 "Met dank aan: A. Gerard, J. Gerber, P. Pahl, J. Bernard"
.define res_string_label_files_remaining "Resterende bestanden: "
.define res_string_copy_label_status "Kopi\x10ren: "
.define res_string_copy_label_from "van:"
.define res_string_copy_label_to "naar:"
.define res_string_move_label_status "Verplaatsen: "
.define res_string_prompt_overwrite "Bestand bestaat al. Overschrijven?"
.define res_string_errmsg_too_large_to_copy "Bestand te groot om te kopi\x10ren."
.define res_string_errmsg_too_large_to_move "Bestand te groot om te verplaatsen."
.define res_string_errmsg_overwrite_dir "Een map kan niet worden vervangen door een ander item. Verwijder het en probeer het opnieuw."
.define res_string_prompt_delete_confirm_singular_format "Weet je zeker dat je %0n bestand permanent wilt verwijderen?"
.define res_string_prompt_delete_confirm_plural_format "Weet je zeker dat je %0n bestanden permanent wilt verwijderen?"
.define res_string_label_delete_count "Wissen: "
.define res_string_label_file "Archief:"
.define res_string_delete_prompt_locked_file "Bestand is beveiligd tegen verwijderen, toch doen?"
.define res_string_get_info_label_name "Naam:"
.define res_string_get_info_label_file_size "Grootte:"
.define res_string_get_info_label_create "Aanmaak:"
.define res_string_get_info_label_mod "Bewerking:"
.define res_string_get_info_label_type "Type:"
.define res_string_get_info_checkbox_locked "Beveiligd"
.define res_string_get_info_shortcut_locked " (^L)"
.define res_string_get_info_label_protected "Schrijfbeveiligd:"
.define res_string_get_info_label_yes "Ja"
.define res_string_get_info_label_no "Nee"
.define res_string_get_info_label_vol_size "Grootte gebruikt/totaal:"
.define res_string_get_info_size_file_format "%0k"
.define res_string_get_info_size_dir_singular_format "%0k voor %1n  onderdeel  "
.define res_string_get_info_size_dir_plural_format "%0k voor %1n  onderdelen  "
.define res_string_get_info_size_vol_singular_format "%0k voor %1n  onderdeel / %2k  "
.define res_string_get_info_size_vol_plural_format "%0k voor %1n  onderdelen / %2k  "
.define res_string_format_disk_label_select "Kies de schijf om te formatteren:"
.define res_string_format_disk_label_location "Locatie: "
.define res_string_format_disk_label_enter_name "Naam nieuw volume:"
.define res_string_format_disk_status_formatting "Bezig met formatteren..."
.define res_string_format_disk_error "Fout bij het formatteren. Controleer het station."
.define res_string_erase_disk_label_select "Selecteer de te formatteren schijf:"
.define res_string_erase_disk_prompt_erase_format "Weet je zeker dat je wilt wissen %0s?"
.define res_string_erase_disk_status_erasing "Wis schijf..."
.define res_string_erase_disk_error "Fout bij het wissen. Controleer station."
.define res_string_tip_copy_prodos "Tip: Kopieer PRODOS naar de schijf om het opstartbaar te maken."
.define res_string_download_error_ramcard_full "The RAMCard is vol. De kopie is niet compleet."
.define res_string_warning_insert_system_disk "Plaats de systeemschijf."
.define res_string_warning_selector_list_full "De lijst is vol. Verwijder een snelkoppeling. voordat je een nieuwe kunt toevoegen."
.define res_string_warning_window_must_be_closed "Sluit eerst een venster. Daarna kun je dit onderdeel openen."
.define res_string_warning_too_many_files "Er zijn te veel bestanden om dit onderdeel te openen!"
.define res_string_warning_too_many_windows "Te veel open vensters op het bureaublad!"
.define res_string_warning_save_changes "Wil je de wijzigingen opslaan op de systeemschijf?"
.define res_string_errmsg_00 "Er is een onbekende fout opgetreden."
.define res_string_errmsg_27 "I/O fout."
.define res_string_errmsg_28 "Apparaat niet aangeslotern."
.define res_string_errmsg_2B "De schijf is beschermd tegen wijziging."
.define res_string_errmsg_40 "De padnaam is te lang of ongeldig."
.define res_string_errmsg_44 "Pad bestaat niet."
.define res_string_errmsg_45 "Volume niet gevonden."
.define res_string_errmsg_46 "Bestand niet gevonden."
.define res_string_errmsg_47 "Deze naam bestaat al."
.define res_string_errmsg_48 "De schijf is vol."
.define res_string_errmsg_49 "De catalogus van het volume is vol."
.define res_string_errmsg_4E "Het bestand is geblokkeerd tegen wijzigen."
.define res_string_errmsg_52 "Dit is geen ProDOS-schijf."
.define res_string_errmsg_57 "Volume bestaat al."
.define res_string_alert_confirm_running "Het uitvoeren van een binair bestand kan de computer crashen. Weet u het zeker?"
.define res_string_alert_bad_replacement "Een item kan niet door zichzelf vervangen worden of door een item dat het bevat."
.define res_string_alert_unsupported_type "Dit bestandstype wordt niet ondersteund."
.define res_string_alert_no_windows_open "Er zijn geen vensters geopend."
.define res_string_alert_move_copy_into_self "Een item kan niet naar zichzlef verplaatst of gekopieerd worden."
.define res_string_alert_duplicate_volume_names "Er zijn 2 volumes met dezelfde naam."
.define res_string_alert_cannot_open "Dit bestand kan niet worden geopend."
.define res_string_alert_name_too_long "De naam is te lang."
.define res_string_alert_insert_source_disk "Plaats de originele schijf."
.define res_string_alert_insert_destination "Plaats de doeldiskette."
.define res_string_alert_insert_disk "Plaats de schijf: %0s"
.define res_string_alert_basic_system_not_found "BASIC.SYSTEM niet gevonden."
.define res_string_alert_unreadable_format "De schijf is onleesbaar. Formatteren?"
.define res_string_trash_icon_name "Prullenmand"
.define res_string_sd_name_format "S%0d,D%1d: %2s"
.define res_string_volume_type_unknown "Onbekend"
.define res_string_auxtype_format "%0s     AuxType: $%1x"
.define res_string_folder "Map"
.define res_string_volume "Schijfvolume"
.define res_string_volume_type_disk_ii "Disk II"
.define res_string_volume_type_ramcard "RAMCard"
.define res_string_volume_type_fileshare "AppleShare"
.define res_string_volume_type_vdrive "ADTPro VDRIVE"
.define res_string_selector_label_enter_name "Naam snelkoppeling:"
.define res_string_selector_label_add_a_new_entry_to "Snelkoppeling weergeven in:"
.define res_string_selector_label_primary_run_list "aan menu en lijst"
.define res_string_selector_label_secondary_run_list "aan alleen lijst"
.define res_string_selector_label_download "Kopi\x10ren naar RAMCard:"
.define res_string_selector_label_at_first_boot "tijdens het opstarten"
.define res_string_selector_label_at_first_use "bij eerste gebruik"
.define res_string_selector_label_never "nooit"
.define res_string_the_dos_33_disk_format "de DOS 3.3-schijf in slot %0d schijfstation %1d"
.define res_string_the_disk_in_slot_format "de schijf in slot %0d schijfstation %1d"
.define res_string_file_count_singular_format "%0n bestand"
.define res_string_file_count_plural_format "%0n bestanden"
.define res_string_kb_suffix "K"
.define res_string_menu_item_slot_pattern "Slot #"
.define res_const_menu_item_slot_pattern_offset1 6
.define res_string_menu_item_add_entry "Een snelkoppeling toevoegen..."
.define res_string_menu_item_edit_entry "Een snelkoppeling bewerken..."
.define res_string_menu_item_delete_entry "Een snelkoppeling verwijderen..."
.define res_string_menu_item_run_entry "Voer een snelkoppeling uit..."
.define res_string_menu_item_about "Over Apple II DeskTop"
.define res_string_menu_item_about_this_apple "Over deze Apple II"
.define res_string_window_header_item_count_singular_format "%0n onderdeel"
.define res_string_window_header_item_count_plural_format "%0n onderdelen"
.define res_string_window_header_k_used_format "%0k op schijf"
.define res_string_window_header_k_available_format "%0k beschikbaar"
.define res_string_no_date "geen datum"
.define res_string_datetime_format "%0s om %1s"
.define res_string_mdy_format "%1s %0d, %2d"
.define res_string_dmy_format "%0d %1s %2d"
.define res_string_today "Vandaag"
.define res_string_yesterday "Gisteren"
.define res_string_tomorrow "Morgen"
