.define res_string_window_title "Regelpaneel"
.define res_string_label_pattern "Patroon bureaublad instellen"
.define res_string_label_rgb_color "RGB-kleur"
.define res_string_label_dblclick_speed "Dubbelkliksnelheid"
.define res_string_label_mouse_tracking "Muisbeweging"
.define res_string_label_slow "Langzaam"
.define res_string_label_fast "Snel"
.define res_string_label_ipblink1 "Knippersnelheid"
.define res_string_label_ipblink2 "invoegpunt"
