.define res_string_window_title "Weergaven"
.define res_string_initial_view "Initi\x10le weergavestijl:"
.define res_string_radio_button_by_icon "als Symbolen"
.define res_string_radio_button_by_small_icon "als Kleine Symbolen"
.define res_string_radio_button_by_name "op Naam"
.define res_string_radio_button_by_date "op Datum"
.define res_string_radio_button_by_size "op Grootte"
.define res_string_radio_button_by_type "op Soort"
