#!/usr/bin/env bash

# Compute MD5 checksums of build targets. Useful when doing no-op
# changes to the code (e.g. bulk label renames) to ensure that no
# output changes were introduced.

MD5=$((which -s md5 && echo 'md5') || (which -s md5sum && echo 'md5sum'))

$MD5 $(find */out -name '*.da' -o -name '*.seg' -o -name '*.SYS')
