.define res_string_window_title "Panel de Control"
.define res_string_label_pattern "Establecer Patr\x13n de Pantalla"
.define res_string_label_rgb_color "Color RGB"
.define res_string_label_dblclick_speed "Velocidad de doble-click"
.define res_string_label_mouse_tracking "Movimiento de Rat\x13n"
.define res_string_label_slow "Lento"
.define res_string_label_fast "R\x10pido"
.define res_string_label_ipblink1 "Velocidad de Inserci\x13n"
.define res_string_label_ipblink2 "Punto Parpadeando"
