.define res_string_window_title "Opties"
.define res_string_label_ramcard "Kopieer naar RAMCard (als aanwezig)"
.define res_string_label_selector "Toon Opdrachten bij opstarten"
.define res_string_label_shortcuts "Toon sneltoetsen in dialoogvensters"
.define res_string_label_case "Behoud hoofdletters en kleine letters in namen"
.define res_string_label_invisible "Toon onzichtbare bestanden"
