--[[ BEGINCONFIG ========================================

DISKARGS="-hard1 $HARDIMG -hard2 tests.hdv"

======================================== ENDCONFIG ]]

a2d.ConfigureRepaintTime(0.25)

a2d.SelectPath("/A2.DESKTOP")
local vol_icon_x, vol_icon_y = a2dtest.GetSelectedIconCoords()
a2d.ClearSelection()

function disabled(r, str)
  test.Expect(not r:find(str), str .. " should be disabled", {}, 1)
end
function enabled(r, str)
  test.Expect(r:find(str), str .. " should be enabled", {}, 1)
end

test.Step(
  "No selection, no windows",
  function()
    a2d.ClearSelection()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "New Folder")
    disabled(ocr, "Open")
    disabled(ocr, "Close  ") -- Spaces to distinguish from Close All"
    disabled(ocr, "Close All")
    disabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    disabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "as Icons")
    disabled(ocr, "as Small Icons")
    disabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "No selection, open window",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.ClearSelection()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    disabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    disabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    disabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
    a2d.CloseAllWindows()
end)

test.Step(
  "Trash selected, no window",
  function()
    a2d.Select("Trash")
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "New Folder")
    disabled(ocr, "Open")
    disabled(ocr, "Close  ")
    disabled(ocr, "Close All")
    disabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    disabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "as Icons")
    disabled(ocr, "as Small Icons")
    disabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Trash selected, open window",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.SelectPath("/Trash", {keep_windows=true})
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    disabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    disabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    disabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
    a2d.CloseAllWindows()
end)

test.Step(
  "Volume selected, no windows",
  function()
    a2d.Select("A2.DESKTOP")
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "New Folder")
    enabled(ocr, "Open")
    disabled(ocr, "Close  ")
    disabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    enabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Cut")
    enabled(ocr, "Copy")
    enabled(ocr, "Paste")
    enabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "as Icons")
    disabled(ocr, "as Small Icons")
    disabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Volume selected, open window",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.SelectPath("/A2.DESKTOP", {keep_windows=true})
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    enabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Cut")
    enabled(ocr, "Copy")
    enabled(ocr, "Paste")
    enabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
    a2d.CloseAllWindows()
end)

test.Step(
  "Multiple volumes selected, no windows",
  function()
    a2d.DragSelectMultipleVolumes()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "New Folder")
    enabled(ocr, "Open")
    disabled(ocr, "Close  ")
    disabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "as Icons")
    disabled(ocr, "as Small Icons")
    disabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Multiple volumes selected, open window",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.DragSelectMultipleVolumes()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
    a2d.CloseAllWindows()
end)

test.Step(
  "Volumes and Trash selected, no windows",
  function()
    a2d.SelectAll()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "New Folder")
    enabled(ocr, "Open")
    disabled(ocr, "Close  ")
    disabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "as Icons")
    disabled(ocr, "as Small Icons")
    disabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Volumes and Trash selected, open window",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.ClearSelectionAndFocusDesktop()
    a2d.SelectAll()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    disabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    enabled(ocr, "Check Drive")
    enabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
    a2d.CloseAllWindows()
end)

test.Step(
  "Single non-alias file selected, open window",
  function()
    a2d.SelectPath("/A2.DESKTOP/READ.ME")
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    enabled(ocr, "Rename")
    enabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    enabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Cut")
    enabled(ocr, "Copy")
    enabled(ocr, "Paste")
    enabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    enabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Single alias file selected, open window",
  function()
    a2d.SelectPath("/TESTS/ALIASES/BASIC.ALIAS")
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    enabled(ocr, "Rename")
    enabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    enabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Cut")
    enabled(ocr, "Copy")
    enabled(ocr, "Paste")
    enabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    enabled(ocr, "Make Alias")
    enabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

test.Step(
  "Multiple files, open window",
  function()
    a2d.OpenPath("/TESTS/FILE.TYPES")
    a2d.SelectAll()
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Open")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    enabled(ocr, "Get Info")
    disabled(ocr, "Rename")
    disabled(ocr, "Duplicate")
    enabled(ocr, "Copy To...")
    enabled(ocr, "Delete")
    enabled(ocr, "Quit")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.EDIT_MENU)
    local ocr = a2dtest.OCRScreen()
    disabled(ocr, "Cut")
    disabled(ocr, "Copy")
    disabled(ocr, "Paste")
    disabled(ocr, "Clear")
    enabled(ocr, "Select All")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.VIEW_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "as Icons")
    enabled(ocr, "as Small Icons")
    enabled(ocr, "by Name")
    apple2.EscapeKey()
    a2d.OpenMenu(a2d.SPECIAL_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "Check All Drives")
    disabled(ocr, "Check Drive")
    disabled(ocr, "Eject Disk")
    enabled(ocr, "Format Disk...")
    enabled(ocr, "Erase Disk...")
    enabled(ocr, "Copy Disk...")
    disabled(ocr, "Make Alias")
    disabled(ocr, "Show Original")
    apple2.EscapeKey()
end)

--[[
  Launch DeskTop. Open a window. Verify that File > New Folder, File >
  Close, File > Close All, and everything in the View menu are
  enabled.
]]
test.Step(
  "File menu options needing window are correct",
  function()
    a2d.OpenPath("/A2.DESKTOP")
    a2d.OpenMenu(a2d.FILE_MENU)
    local ocr = a2dtest.OCRScreen()
    enabled(ocr, "New Folder")
    enabled(ocr, "Close  ")
    enabled(ocr, "Close All")
    apple2.EscapeKey()
end)

test.Step(
  "Control-Shift-2 doesn't show first menu item without shortcut",
  function()
    a2dtest.ExpectNothingChanged(function()
        apple2.ControlKey("@")
        a2d.WaitForRepaint()
    end)
end)
