.define res_string_alert_selector_unable_to_run "No puede ejecutar el programa."
.define res_string_alert_io_error "Error de E/S."
.define res_string_alert_no_device "Ning\x14n dispositivo conectado."
.define res_string_alert_pathname_does_not_exist "Parte de la ruta no existe."
.define res_string_alert_insert_source_disk "Por favor inserte el disco fuente."
.define res_string_alert_file_not_found "El archivo no se puede encontrar."
.define res_string_alert_insert_system_disk "Por favor inserte el disco de sistema."
.define res_string_alert_basic_system_not_found "No se encuentra el BASIC.SYSTEM."
.define res_string_menu_bar_item_file "Archivo"
.define res_string_menu_bar_item_startup "Arranque"
.define res_string_menu_item_run_a_program "Ejecutar un Programa..."
.define res_char_menu_item_run_a_program_shortcut 'R'
.define res_string_menu_item_slot_pattern "Ranura #"
.define res_const_menu_item_slot_pattern_offset1 8
.define res_string_button_desktop "Escritorio"
.define res_char_button_desktop_shortcut 'E'
.define res_string_selector_name "Atajos"
.define res_string_label_download "Copiando a RAMDisk..."
.define res_string_label_copying "Copiando: "
.define res_string_errmsg_not_enough_room "No hay sitio suficiente en la RAMDisk para copiar la aplicaci\x13n."
.define res_string_prompt_click_ok "Presiona OK para continuar."
.define res_string_errmsg_error_download "Ha ocurrido un error durante la descarga."
.define res_string_errmsg_copy_incomplete "La copia no se ha completado."
.define res_string_label_files_to_copy "Archivos por copiar a la RAMDisk: "
.define res_string_label_files_remaining "Archivos que quedan por copiar: "
.define res_string_label_file_to_run "Archivo a ejecutar:"
