.define res_string_alert_selector_unable_to_run "Kan het programma niet uitvoeren."
.define res_string_alert_io_error "I/O fout."
.define res_string_alert_no_device "Apparaat niet aangeslotern."
.define res_string_alert_pathname_does_not_exist "Pad bestaat niet."
.define res_string_alert_insert_source_disk "Plaats de originele schijf."
.define res_string_alert_file_not_found "Bestand niet gevonden."
.define res_string_alert_insert_system_disk "Plaats de systeemschijf."
.define res_string_alert_basic_system_not_found "BASIC.SYSTEM niet gevonden."
.define res_string_menu_bar_item_file "Archief"
.define res_string_menu_bar_item_startup "Opstart"
.define res_string_menu_item_run_a_program "Een programma uitvoeren..."
.define res_char_menu_item_run_a_program_shortcut 'E'
.define res_string_menu_item_slot_pattern "Slot #"
.define res_const_menu_item_slot_pattern_offset1 6
.define res_string_button_desktop "Bureaublad"
.define res_char_button_desktop_shortcut 'B'
.define res_string_selector_name "Opdrachten"
.define res_string_label_download "Kopi\x10ren naar RAMCard..."
.define res_string_label_copying "Kopi\x10ren: "
.define res_string_errmsg_not_enough_room "Niet genoeg ruimte op de RAMCard om de applicatie te kopi\x10ren."
.define res_string_errmsg_copy_incomplete "Er is een fout opgetreden. De kopie is niet voltooid."
.define res_string_label_files_to_copy "Bestanden om te kopi\x10ren: "
.define res_string_label_files_remaining "Resterende bestanden: "
