.define res_string_label_download "Copiando a Tarjeta de Memoria..."
.define res_string_label_copying "Copiando:"
.define res_string_errmsg_not_enough_room "No hay sitio suficiente en la tarjeta de memoria para copiar la aplicacion."
.define res_string_prompt_click_ok "Presiona OK para continuar."
.define res_string_errmsg_error_download "Ha ocurrido un error durante la descarga."
.define res_string_errmsg_copy_incomplete "La copia no se ha completado, presione OK para continuar."
.define res_string_label_files_to_copy "Archivos por copiar a la tarjeta de memoria: "
.define res_string_label_files_remaining "Archivos que quedan por copiar: "
