.define res_string_add_an_entry_dialog_title "A|adir Entrada..."
.define res_string_edit_an_entry_dialog_title "Editar Entrada..."
.define res_string_delete_an_entry_dialog_title "Borrar Entrada..."
.define res_string_run_an_entry_dialog_title "Ejecutar Entrada..."
.define res_string_selector_label_enter_pathname "Escriba la ruta completa del archivo de ejecucion:"
.define res_string_selector_label_enter_name "Escriba el nombre (14 caracteres max.):"
.define res_string_selector_label_add_a_new_entry_to "A|ada entrada a la:"
.define res_string_selector_label_run_list "1 Lista de ejecucion"
.define res_string_selector_label_other_run_list "2 Otra lista"
.define res_string_selector_label_download "Copiar a RAMDisk:"
.define res_string_selector_label_at_first_boot "3 en el arranque"
.define res_string_selector_label_at_first_use "4 por primera vez"
.define res_string_selector_label_never "5 nunca"
.define res_string_the_dos_33_disk_suffix_pattern "el disco DOS 3.3 en la ranura # unidad # ?"
.define res_const_the_dos_33_disk_suffix_pattern_offset1 31
.define res_const_the_dos_33_disk_suffix_pattern_offset2 40
.define res_string_the_disk_in_slot_suffix_pattern "el disco en la ranura # unidad #?"
.define res_const_the_disk_in_slot_suffix_pattern_offset1 23
.define res_const_the_disk_in_slot_suffix_pattern_offset2 32
.define res_string_files_suffix "Archivos"
.define res_string_kb_suffix "K"
.define res_string_button_change_drive "Cambiar unidad"
.define res_string_button_open "Abrir"
.define res_string_button_close "Cerrar"
.define res_string_fd_button_cancel "Cancelar    Esc"
.define res_string_fd_button_ok "OK            \x0D"
.define res_string_label_disk " Disco: "
.define res_string_copy_file_dialog_title "Copiar un archivo..."
.define res_string_copy_file_label_source_filename "Nombre del archivo original:"
.define res_string_copy_file_label_destination_filename "Nombre del archivo de destino:"
.define res_string_delete_file_dialog_title "Borrar un archivo..."
.define res_string_delete_file_label_file_to_delete "Archivo a borrar:"
.define res_string_weekday_abbrev_1 "Dom "
.define res_string_weekday_abbrev_2 "Lun "
.define res_string_weekday_abbrev_3 "Mar "
.define res_string_weekday_abbrev_4 "Mie "
.define res_string_weekday_abbrev_5 "Jue "
.define res_string_weekday_abbrev_6 "Vie "
.define res_string_weekday_abbrev_7 "Sab "
.define res_string_menu_item_slot_pattern "Ranuar #"
.define res_const_menu_item_slot_pattern_offset1 8
.define res_string_menu_item_add_entry "A|adir entrada..."
.define res_string_menu_item_edit_entry "Editar entrada..."
.define res_string_menu_item_delete_entry "Borrar Entrada..."
.define res_string_menu_item_run_entry "Ejecutar entrada..."
.define res_string_menu_item_about "Acerca %s"
.define res_string_splash_menu_label "%s Version %d.%d%s"
.define res_string_window_header_items_suffix " Elementos"
.define res_string_window_header_k_used_suffix "K en disco"
.define res_string_window_header_k_available_suffix "K disponible"
